#pragma once

// Game events a stock CS2 client never subscribes to, and that an injected library observing the
// game ends up asking for. Normal client and game-instructor subscriptions are deliberately absent,
// so any hit is a real signal.

#include <array>
#include <string_view>

namespace Anticheat
{

inline constexpr std::array<std::string_view, 117> DllEventBlacklist = {
    "gameui_hidden",
    "player_chat",
    "player_score",
    "player_shoot",
    "game_init",
    "game_start",
    "game_end",
    "ugc_map_info_received",
    "ugc_map_unsubscribed",
    "ugc_map_download_error",
    "ugc_file_download_finished",
    "ugc_file_download_start",
    "dm_bonus_weapon_start",
    "survival_announce_phase",
    "reset_game_titledata",
    "vote_ended",
    "vote_started",
    "vote_options",
    "endmatch_mapvote_selecting_map",
    "endmatch_cmm_start_reveal_items",
    "inventory_updated",
    "client_loadout_changed",
    "add_player_sonar_icon",
    "door_open",
    "door_closed",
    "door_break",
    "bullet_damage",
    "hostage_call_for_help",
    "vip_escaped",
    "vip_killed",
    "silencer_detach",
    "inspect_weapon",
    "player_spawned",
    "item_pickup_slerp",
    "item_pickup_failed",
    "enter_rescue_zone",
    "exit_rescue_zone",
    "silencer_off",
    "silencer_on",
    "round_poststart",
    "tagrenade_detonate",
    "inferno_extinguish",
    "mb_input_lock_success",
    "mb_input_lock_cancel",
    "nav_generate",
    "achievement_info_loaded",
    "hltv_changed_mode",
    "show_deathpanel",
    "hide_deathpanel",
    "player_avenged_teammate",
    "achievement_earned_local",
    "repost_xbox_achievements",
    "match_end_conditions",
    "write_profile_data",
    "trial_time_expired",
    "update_matchmaking_stats",
    "enable_restart_voting",
    "sfuievent",
    "start_vote",
    "teamchange_pending",
    "material_default_complete",
    "cs_prev_next_spectator",
    "tournament_reward",
    "start_halftime",
    "ammo_refill",
    "parachute_pickup",
    "parachute_deploy",
    "dronegun_attack",
    "drone_dispatched",
    "loot_crate_visible",
    "loot_crate_opened",
    "open_crate_instr",
    "smoke_beacon_paradrop",
    "drone_cargo_detached",
    "drone_above_roof",
    "dz_item_interaction",
    "survival_teammate_respawn",
    "guardian_wave_restart",
    "bullet_flight_resolution",
    "server_message",
    "player_full_update",
    "local_player_controller_team",
    "local_player_pawn_changed",
    "ragdoll_dissolved",
    "team_info",
    "team_score",
    "hltv_rank_camera",
    "hltv_rank_entity",
    "demo_stop",
    "map_shutdown",
    "hostname_changed",
    "game_message",
    "round_start_pre_entity",
    "round_start_post_nav",
    "player_hintmessage",
    "broken_breakable",
    "door_close",
    "vote_failed",
    "vote_passed",
    "vote_cast_yes",
    "vote_cast_no",
    "achievement_event",
    "achievement_write_failed",
    "bonus_updated",
    "flare_ignite_npc",
    "helicopter_grenade_punt_miss",
    "physgun_pickup",
    "cart_updated",
    "store_pricesheet_updated",
    "item_schema_initialized",
    "drop_rate_modified",
    "event_ticket_modified",
    "gc_connected",
    "instructor_start_lesson",
    "instructor_close_lesson",
    "clientside_lesson_closed",
    "dynamic_shadow_light_changed",
};

static_assert(DllEventBlacklist.size() == 117, "The DLL injection event list must contain 117 entries.");

}  // namespace Anticheat
