services:
  build:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
      target: build
    working_dir: /app
    volumes:
      - ..:/app
    command: bash deploy/scripts/build-plugin.sh
